include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - avoid_empty_else
    - avoid_relative_lib_imports
    - avoid_web_libraries_in_flutter
    - no_duplicate_case_values
    - null_closures
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_contains
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_final_locals
    - public_member_api_docs
    - sort_child_properties_last
    - sort_pub_dependencies
    - unnecessary_overrides
    - use_full_hex_values_for_flutter_colors
    - valid_regexps
